# Nord theme for Alacritty
# https://github.com/arcticicestudio/nord-alacritty
[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

# MonoLisa font patched with Nerd Font glyphs is in your Google Drive
[font.bold]
family = "MonoLisa Nerd Font"
style = "Bold"

[font.italic]
family = "MonoLisa Nerd Font"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

# adding a small line offset makes the vertical lines smooth when using MonoLisa
[font.offset]
y = -2

[shell]
args = ["-c", "/opt/homebrew/bin/tmux new-session -A -s main"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
# needed to correctly handle option key in broot
option_as_alt = "Both"
startup_mode = "Maximized"
