#!/bin/bash

set -e

# Install Homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

# Install Homebrew packages from Brewfile
brew bundle --file dotfiles/brew/Brewfile
