#!/bin/bash

set -e


# Install curl, some distributions don't have it installed upfront

sudo apt install curl --yes


# Add apt repositories and update apt

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "ppa:mmstick76/alacritty" --no-update --yes
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" --no-update --yes

sudo apt update


# Install apt packages
# Necessary for Alacritty, Docker, Homebrew and some of the Vim plugins

sudo apt install --yes \
    alacritty \
    apache2-utils \
    apt-transport-https \
    build-essential \
    ca-certificates \
    cmake \
    containerd.io \
    curl \
    docker-ce \
    docker-ce-cli \
    exuberant-ctags \
    file \
    git \
    gnupg-agent \
    pm-utils \
    python3-dev \
    software-properties-common


# Add user to docker group

sudo groupadd docker -f
sudo usermod -aG docker $USER


# Install snap packages 
# Has to be in separate lines as classic snaps can't be installed in a single command.
                
sudo snap install code --classic
sudo snap install goland --classic
sudo snap install pycharm-professional --classic
sudo snap install postman 


# Install Homebrew 

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"


# Add Homebrew to PATH so that packages can be installed below
# We're setting SHELL to "bash" temporarily because this script is execeuted with #!/bin/bash
# Otherwise bootstrap wouldn't work if executed from fish shell
eval $(SHELL=/bin/bash /home/linuxbrew/.linuxbrew/bin/brew shellenv)


# Install Homebrew packages from Brewfile

brew bundle --file dotfiles/brew/Brewfile

