#!/bin/bash

set -e

TOOLS_DIR=~/workspace/tools
BIN_DIR=~/.local/bin

apt_repos=(
    "ppa:mmstick76/alacritty"
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
)

apt_pkgs=(
    "alacritty"
    "apt-transport-https"
    "ca-certificates"
    "containerd.io"
    "curl"
    "docker-ce"
    "docker-ce-cli"
    "fish"
    "gnupg-agent"
    "go-dep"
    "htop"
    "pm-utils"
    "software-properties-common"
    "tig"
    "tmux"
    "vagrant"
    "vim"
)

snaps=(
   "code" 
   "fluxctl" 
   "go" 
   "goland" 
   "helm" 
   "hugo" 
   "jq" 
   "kubectl" 
   "postman" 
   "pycharm-professional" 
   "starship"
)

# Add apt repos
for apt_repo in "${apt_repos[@]}"
do
    sudo add-apt-repository "$apt_repo" --no-update --yes
done

# Update apt
sudo apt update

# Install apt packages
for apt_pkg in "${apt_pkgs[@]}"
do
    sudo apt install "$apt_pkg" 
done

# Install snap packages
for snap in "${snaps[@]}"
do
    sudo snap install $snap --classic
done
