---
- hosts: localhost
  connection: local

  vars:
    snap_classic_pkgs:
      - code

    apt_repos:
      - ppa:mmstick76/alacritty

    apt_pks:
      - fish
      - alacritty

  tasks:
  - name: Ensure workspace directory
    file:
      path: ~/workspace
      state: directory
      
  - name: Install snaps
    become: yes
    snap:
      name: "{{ item }}"
      classic: yes
    loop: "{{ snap_classic_pkgs }}"	

  - name: Add apt repos
    become: yes
    apt_repository:
      repo: "{{ item }}"
      state: present
      update_cache: yes
    loop: "{{ apt_repos }}" 
      
  - name: Install apt packages
    become: yes
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop: "{{ apt_pks }}"