# Default prompt order but push kubernetes towards the end of the prompt
format = """\
   $username\
   $hostname\
   $directory\
   $git_branch\
   $git_commit\
   $git_state\
   $git_status\
   $hg_branch\
   $package\
   $dotnet\
   $elixir\
   $elm\
   $golang\
   $haskell\
   $java\
   $julia\
   $nodejs\
   $php\
   $python\
   $ruby\
   $rust\
   $terraform\
   $nix_shell\
   $conda\
   $memory_usage\
   $kubernetes\
   $aws\
   $env_var\
   $crystal\
   $cmd_duration\
   $line_break\
   $jobs\
   $battery\
   $time\
   $character\
"""

[kubernetes]
symbol = "⛵"
style = "245"
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[aws]
symbol = "⛅"
format = '[($symbol($profile ))]($style)'

[git_branch]
symbol = "🌱"
