return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	tag = "v0.10.0",
	build = ":TSUpdate",

	opts = {
		ensure_installed = {
			"bash",
			"c",
			"dockerfile",
			"fish",
			"gitignore",
			"go",
			"gomod",
			"helm",
			"html",
			"javascript",
			"json",
			"lua",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"requirements",
			"sql",
			"terraform",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		sync_install = false,
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
	},
}
