set nocompatible
let $VIMHOME = $HOME."/.vim"

" Automatically install vim-plug
" https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif


call plug#begin($VIMHOME."/vim-plug-plugins")

Plug 'arcticicestudio/nord-vim'
Plug 'airblade/vim-gitgutter'
Plug 'itchyny/lightline.vim'
Plug 'preservim/nerdtree'

call plug#end()

" General

set backspace=indent,eol,start	" Backspace behaviour
set history=1000                " Bigger history
set undolevels=1000		" Bigger number of undo levels
set showcmd                     " Show incomplete commands
set shortmess+=F                " Don't show the file name in the command line bar
set showmode                    " Show current mode
set autoread                    " Automatically re-read files if unmodified inside Vim
set hidden                      " Manage multiple buffers effectively

" User interface

colorscheme nord                " Set color scheme
set laststatus=2                " Always show the status bar
set ruler                       " Show cursor position
set wildmenu                    " Show command line’s tab complete options as a menu
set cursorline                  " Highlight line under cursor
set linebreak			" Break lines at word (requires Wrap lines) 
set number                      " Show line numbers
set relativenumber              " Show relative line numbers
set noerrorbells                " Disable beep on errors
set mouse=a                     " Enable mouse for scrolling an resizing
set title                       " Show filename in windows title

" Swap, undo and backup

if !isdirectory($VIMHOME.'/.swp')
    call mkdir($VIMHOME.'/.swp')
endif

set directory=$VIMHOME/.swp//

if !isdirectory($VIMHOME.'/.undo')
    call mkdir($VIMHOME.'/.undo')
endif

set undofile
set undodir=$VIMHOME/.undo//

if !isdirectory($VIMHOME.'/.backup')
    call mkdir($VIMHOME.'/.backup')
endif

set backupdir=$VIMHOME/.backup//

" Indentation

set autoindent			" Auto-indent new lines
set expandtab			" Use spaces instead of tabs
filetype plugin indent on       " Smart auto indentation
set shiftwidth=4		" Number of auto-indent spaces
set smarttab			" Enable smart-tabs
set softtabstop=4		" Number of spaces per Tab

" Search

set showmatch			" Highlight matching brace 
set hlsearch			" Highlight all search results
set smartcase			" Enable smart-case search
set ignorecase			" Always case-insensitive
set incsearch			" Searches for strings incrementally
 
" Text rendering

set encoding=utf-8              " Use unicode
set nowrap                      " Don't wrap lines
set scrolloff=3                 " Number of lines to show above and below cursor
set sidescrolloff=5             " Number of columns to show left and right of cursor
syntax on                       " Enable syntax highlighting 
set spell                       " Enable spell checking


" Lightline configuration

set laststatus=2
set noshowmode
if !has('gui_running')
    set t_Co=256
endif


" NERTTree configuration

nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>

" Exit Vim if NERDTree is the only window left.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif


" Other configuration

set updatetime=100             " Make the gitgutter updates faster

