gui:
  showRandomTip: false
  showCommandLog: false
  expandFocusedSidePanel: true

  theme:
    # Needed to make the selected line visible in Alacritty
    # https://github.com/jesseduffield/lazygit/issues/831
    selectedLineBgColor:
      - reverse
    activeBorderColor:
      - "#5E81AC"
      - bold
    inactiveBorderColor:
      - "#4C566A"

  authorColors:
    "Grzegorz Dlugoszewski": "#5E81AC"
    "Greg Dlugoszewski": "#5E81AC"

keybinding:
  universal:
    appendNewline: "<tab>"

os:
  editCommand: "lvim"

git:
  log:
    showGraph: always

  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never
