gui:
  theme:
    # Needed to make the selected line visible in Alacritty
    # https://github.com/jesseduffield/lazygit/issues/831
    selectedLineBgColor:
      - reverse

keybinding:
  universal:
    appendNewline: '<tab>'
